export const ID_TYPES = [
  { value: 'CC', label: 'Cédula de Ciudadanía' },
  { value: 'TI', label: 'Tarjeta de Identidad' },
  { value: 'CE', label: 'Cédula de Extranjería' },
  { value: 'PP', label: 'Pasaporte' },
];

export const COUNTRY_CODES = [
  { code: '+57', country: 'Colombia' },
  { code: '+52', country: 'México' },
  { code: '+51', country: 'Perú' },
  { code: '+54', country: 'Argentina' },
  { code: '+56', country: 'Chile' },
  { code: '+58', country: 'Venezuela' },
  { code: '+593', country: 'Ecuador' },
  { code: '+507', country: 'Panamá' },
  { code: '+591', country: 'Bolivia' },
  { code: '+595', country: 'Paraguay' },
  { code: '+598', country: 'Uruguay' },
  { code: '+506', country: 'Costa Rica' },
  { code: '+503', country: 'El Salvador' },
  { code: '+502', country: 'Guatemala' },
  { code: '+504', country: 'Honduras' },
  { code: '+505', country: 'Nicaragua' },
  { code: '+1', country: 'USA/Canadá' },
  { code: '+34', country: 'España' },
  { code: '+55', country: 'Brasil' },
  { code: '+44', country: 'Reino Unido' },
  { code: '+49', country: 'Alemania' },
  { code: '+33', country: 'Francia' },
  { code: '+39', country: 'Italia' },
  { code: '+81', country: 'Japón' },
  { code: '+86', country: 'China' },
  { code: '+91', country: 'India' },
];
